package acs.modal;

// Generated 9 nov. 2017 13:43:22 by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;

/**
 * AcsEnrollCheckId generated by hbm2java
 */
public class AcsEnrollCheckId implements java.io.Serializable {

	private Date vedate;
	private String cardNumber;
	private String merurl;
	private String acqbin;
	private String merid;
	private String password;
	private Clob vereq;
	private Clob veres;
	private String enrolled;
	private String msg;

	public AcsEnrollCheckId() {
	}

	
	
	public AcsEnrollCheckId(Date vedate, String cardNumber, String merurl,
			String acqbin, String merid, String password, Clob vereq,
			Clob veres, String enrolled, String msg) {
		super();
		this.vedate = vedate;
		this.cardNumber = cardNumber;
		this.merurl = merurl;
		this.acqbin = acqbin;
		this.merid = merid;
		this.password = password;
		this.vereq = vereq;
		this.veres = veres;
		this.enrolled = enrolled;
		this.msg = msg;
	}



	public Date getVedate() {
		return this.vedate;
	}

	public void setVedate(Date vedate) {
		this.vedate = vedate;
	}

	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	public String getMerurl() {
		return this.merurl;
	}

	public void setMerurl(String merurl) {
		this.merurl = merurl;
	}

	public String getAcqbin() {
		return this.acqbin;
	}

	public void setAcqbin(String acqbin) {
		this.acqbin = acqbin;
	}

	public String getMerid() {
		return this.merid;
	}

	public void setMerid(String merid) {
		this.merid = merid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Clob getVereq() {
		return this.vereq;
	}

	public void setVereq(Clob vereq) {
		this.vereq = vereq;
	}

	public Clob getVeres() {
		return veres;
	}

	public void setVeres(Clob veres) {
		this.veres = veres;
	}

	public String getEnrolled() {
		return enrolled;
	}

	public void setEnrolled(String enrolled) {
		this.enrolled = enrolled;
	}

	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcsEnrollCheckId))
			return false;
		AcsEnrollCheckId castOther = (AcsEnrollCheckId) other;

		return ((this.getVedate() == castOther.getVedate()) || (this
				.getVedate() != null && castOther.getVedate() != null && this
				.getVedate().equals(castOther.getVedate())))
				&& ((this.getCardNumber() == castOther.getCardNumber()) || (this
						.getCardNumber() != null
						&& castOther.getCardNumber() != null && this
						.getCardNumber().equals(castOther.getCardNumber())))
				&& ((this.getMerurl() == castOther.getMerurl()) || (this
						.getMerurl() != null && castOther.getMerurl() != null && this
						.getMerurl().equals(castOther.getMerurl())))
				&& ((this.getAcqbin() == castOther.getAcqbin()) || (this
						.getAcqbin() != null && castOther.getAcqbin() != null && this
						.getAcqbin().equals(castOther.getAcqbin())))
				&& ((this.getMerid() == castOther.getMerid()) || (this
						.getMerid() != null && castOther.getMerid() != null && this
						.getMerid().equals(castOther.getMerid())))
				&& ((this.getPassword() == castOther.getPassword()) || (this
						.getPassword() != null
						&& castOther.getPassword() != null && this
						.getPassword().equals(castOther.getPassword())))
				&& ((this.getVereq() == castOther.getVereq()) || (this
						.getVereq() != null && castOther.getVereq() != null && this
						.getVereq().equals(castOther.getVereq())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getVedate() == null ? 0 : this.getVedate().hashCode());
		result = 37
				* result
				+ (getCardNumber() == null ? 0 : this.getCardNumber()
						.hashCode());
		result = 37 * result
				+ (getMerurl() == null ? 0 : this.getMerurl().hashCode());
		result = 37 * result
				+ (getAcqbin() == null ? 0 : this.getAcqbin().hashCode());
		result = 37 * result
				+ (getMerid() == null ? 0 : this.getMerid().hashCode());
		result = 37 * result
				+ (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37 * result
				+ (getVereq() == null ? 0 : this.getVereq().hashCode());
		return result;
	}

}
