package acs.modal;

// Generated 9 nov. 2017 13:43:22 by Hibernate Tools 3.4.0.CR1

/**
 * AcsEnrollCheck generated by hbm2java
 */
public class AcsEnrollCheck implements java.io.Serializable {

	private AcsEnrollCheckId id;

	public AcsEnrollCheck() {
	}

	public AcsEnrollCheck(AcsEnrollCheckId id) {
		this.id = id;
	}

	public AcsEnrollCheckId getId() {
		return this.id;
	}

	public void setId(AcsEnrollCheckId id) {
		this.id = id;
	}

}
