package acs.modal;

import java.util.Date;
// Generated 5 déc. 2017 09:35:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FieldDefinition generated by hbm2java
 */

@Entity
@Table(name = "FIELD_DEFINITION")
public class FieldDefinition implements java.io.Serializable {

	private FieldDefinitionId id;
	private String id_1;
	private String title;
	private String value;
	private Date DateValue;
	private String type;
	private Byte position;
	private Character status;
	private String page;

	public FieldDefinition() {
	}

	public FieldDefinition(FieldDefinitionId id) {
		this.id = id;
	}

	public FieldDefinition(FieldDefinitionId id, String id_1, String title,
			String value, String type, Byte position, Character status,
			String page) {
		this.id = id;
		this.id_1 = id_1;
		this.title = title;
		this.value = value;
		this.type = type;
		this.position = position;
		this.status = status;
		this.page = page;
	}

	@EmbeddedId
	@AttributeOverrides({			
		    @AttributeOverride(name = "tag", column = @Column(name = "TAG", length = 50)),
			@AttributeOverride(name = "lang", column = @Column(name = "LANG", length = 3)), 
	})
	public FieldDefinitionId getId() {
		return this.id;
	}

	public void setId(FieldDefinitionId id) {
		this.id = id;
	}
	
	@Column(name = "id_1", length = 50)
	public String getId_1() {
		return this.id_1;
	}

	public void setId_1(String id_1) {
		this.id_1 = id_1;
	}

	@Column(name = "TITLE", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	@Column(name = "VALUE", length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	@Column(name = "TYPE", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	@Column(name = "POSITION", length = 50)
	public Byte getPosition() {
		return this.position;
	}

	public void setPosition(Byte position) {
		this.position = position;
	}
	
	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "PAGE", length = 1)
	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

	public void setDateValue(Date date) {
		// TODO Auto-generated method stub
		
	}

	public Date getDateValue() {
		return DateValue;
	}

}
