package acs.modal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PageAccessParam generated by MyEclipse Persistence Tools
 */

@Entity
@Table(name = "PAGE_ACCESS_PARAM")
public class PageAccessParam implements java.io.Serializable {

	// Fields

	private PageAccessParamId id;

	
	public PageAccessParam() {
	}

	/** full constructor */
	public PageAccessParam(PageAccessParamId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({			
		    @AttributeOverride(name = "role", column = @Column(name = "ROLE", length = 50)),
			@AttributeOverride(name = "page", column = @Column(name = "PAGE", length = 50)), 
	})
	public PageAccessParamId getId() {
		return this.id;
	}

	public void setId(PageAccessParamId id) {
		this.id = id;
	}

}